// Code generated by logcopter-gen; DO NOT EDIT.

package copilot

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-minitrace.pkg.adapters.copilot")
