// Code generated by logcopter-gen; DO NOT EDIT.

package annotate

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-minitrace.cmd.go-minitrace.cmds.annotate")
