package minitracejs

import "github.com/go-go-golems/go-go-goja/pkg/tsgen/spec"

func TypeScriptModule() *spec.Module {
	return &spec.Module{
		Name:        ModuleName,
		Description: "Read-only minitrace query helpers and builder APIs.",
		Functions: []spec.Function{
			{Name: "importer", Returns: spec.Named("ImportBuilder")},
			{Name: "db", Returns: spec.Named("DBBuilder")},
			{Name: "sources", Returns: spec.Named("SourceSetBuilder")},
			{Name: "importPolicy", Returns: spec.Named("ImportPolicyBuilder")},
			{Name: "cache", Returns: spec.Named("CachePolicyBuilder")},
			{Name: "limits", Returns: spec.Named("QueryLimitsBuilder")},
			{Name: "query", Returns: spec.Named("QueryRecipeBuilder")},
			{Name: "view", Returns: spec.Named("ViewPlanBuilder")},
			{Name: "session", Returns: spec.Named("SessionBuilder")},
		},
		RawDTS: []string{
			"export interface RuntimeInfo {",
			"  tableName: string;",
			"  dbPath: string;",
			"  archiveGlob: string[];",
			"  persistLoaded: boolean;",
			"  commandName: string;",
			"}",
			"export interface SQLHelpers {",
			"  string(value: string): string;",
			"  stringIn(value: string | string[]): string;",
			"  like(value: string): string;",
			"}",
			"export const runtime: RuntimeInfo;",
			"export const sql: SQLHelpers;",
			"export interface ValidationResult { valid: boolean; errors?: string[]; }",
			"export interface SourceSummary { kind: string; path?: string; name?: string; }",
			"export interface SourceSet { Summary(): SourceSummary[]; }",
			"export interface SourceSetBuilder {",
			"  File(path: string): SourceSetBuilder;",
			"  Archive(path: string): SourceSetBuilder;",
			"  Files(paths: string[]): SourceSetBuilder;",
			"  Dir(path: string): SourceSetBuilder;",
			"  Glob(pattern: string): SourceSetBuilder;",
			"  Content(content: string): SourceSetBuilder;",
			"  Name(name: string): SourceSetBuilder;",
			"  RuntimeArchives(): SourceSetBuilder;",
			"  Validate(): ValidationResult;",
			"  Build(): SourceSet;",
			"}",
			"export interface ImportPolicy { Summary(): Record<string, unknown>; }",
			"export interface ImportPolicyBuilder {",
			"  AutoConvert(enabled?: boolean): ImportPolicyBuilder;",
			"  NativeOnly(): ImportPolicyBuilder;",
			"  Strict(enabled?: boolean): ImportPolicyBuilder;",
			"  Lenient(): ImportPolicyBuilder;",
			"  Format(format: string): ImportPolicyBuilder;",
			"  Build(): ImportPolicy;",
			"}",
			"export interface CachePolicy { Summary(): Record<string, unknown>; }",
			"export interface CachePolicyBuilder {",
			"  None(): CachePolicyBuilder;",
			"  Memory(): CachePolicyBuilder;",
			"  Disk(): CachePolicyBuilder;",
			"  Auto(): CachePolicyBuilder;",
			"  Dir(path: string): CachePolicyBuilder;",
			"  ForceRebuild(enabled?: boolean): CachePolicyBuilder;",
			"  Build(): CachePolicy;",
			"}",
			"export interface QueryLimits { Summary(): Record<string, unknown>; }",
			"export interface QueryLimitsBuilder {",
			"  Rows(n: number): QueryLimitsBuilder;",
			"  Columns(n: number): QueryLimitsBuilder;",
			"  CellChars(n: number): QueryLimitsBuilder;",
			"  TimeoutMs(n: number): QueryLimitsBuilder;",
			"  RequireOrderBy(enabled?: boolean): QueryLimitsBuilder;",
			"  Build(): QueryLimits;",
			"}",
			"export interface ImportBuilder {",
			"  Content(content: string): ImportBuilder;",
			"  File(path: string): ImportBuilder;",
			"  Name(name: string): ImportBuilder;",
			"  SourcePath(path: string): ImportBuilder;",
			"  AutoDetect(): ImportBuilder;",
			"  Format(format: string): ImportBuilder;",
			"  Strict(enabled?: boolean): ImportBuilder;",
			"  Into(rootDir: string): ImportBuilder;",
			"  SessionID(id: string): ImportBuilder;",
			"  Overwrite(enabled?: boolean): ImportBuilder;",
			"  Detect(): Record<string, unknown>;",
			"  Convert(): ImportBuilder;",
			"  Converted(): Record<string, unknown>;",
			"  Diagnostics(): Array<Record<string, unknown>>;",
			"  Save(): Record<string, unknown>;",
			"}",
			"export interface DBBuilder {",
			"  SQLiteMemory(): DBBuilder;",
			"  SQLiteDiskCache(path?: string): DBBuilder;",
			"  File(path: string): DBBuilder;",
			"  Files(paths: string[]): DBBuilder;",
			"  Archive(path: string): DBBuilder;",
			"  Content(content: string, nameOrOptions?: string | { name?: string }): DBBuilder;",
			"  Glob(pattern: string): DBBuilder;",
			"  RuntimeArchives(): DBBuilder;",
			"  Dir(path: string): DBBuilder;",
			"  MaxRows(n: number): DBBuilder;",
			"  MaxColumns(n: number): DBBuilder;",
			"  MaxCellChars(n: number): DBBuilder;",
			"  Timeout(ms: number): DBBuilder;",
			"  RequireOrderBy(enabled: boolean): DBBuilder;",
			"  AutoConvert(enabled: boolean): DBBuilder;",
			"  StrictConversion(enabled: boolean): DBBuilder;",
			"  Sources(sources: SourceSet): DBBuilder;",
			"  Import(policy: ImportPolicy): DBBuilder;",
			"  Limits(limits: QueryLimits): DBBuilder;",
			"  Cache(policyOrMode?: CachePolicy | string): DBBuilder;",
			"  CacheAuto(path?: string): DBBuilder;",
			"  QueryCommandDefaults(): DBBuilder;",
			"  InteractiveDefaults(cacheDir?: string): DBBuilder;",
			"  CacheDir(path: string): DBBuilder;",
			"  ForceRebuild(enabled?: boolean): DBBuilder;",
			"  sources(): SourceSummary[];",
			"  CacheKey(): Record<string, unknown>;",
			"  Validate(): ValidationResult;",
			"  Build(): DBHandle;",
			"}",
			"export interface DBHandle {",
			"  query(sql: string, ...args: unknown[]): Array<Record<string, unknown>>;",
			"  queryOne(sql: string, ...args: unknown[]): Record<string, unknown>;",
			"  queryResult(sql: string, ...args: unknown[]): Record<string, unknown>;",
			"  schema(): Record<string, unknown>;",
			"  tables(): Array<Record<string, unknown>>;",
			"  stats(): Record<string, unknown>;",
			"  sources(): SourceSummary[];",
			"  diagnostics(): Array<Record<string, unknown>>;",
			"  cacheInfo(): Record<string, unknown>;",
			"  CacheInfo(): Record<string, unknown>;",
			"  close(): void;",
			"}",
			"export interface QueryRecipe {",
			"  name(): string;",
			"  sql(): string;",
			"  args(): unknown[];",
			"  description(): string;",
			"  output(): string;",
			"  toJSON(): Record<string, unknown>;",
			"}",
			"export interface QueryRecipeBuilder {",
			"  SessionSummary(): QueryRecipeBuilder;",
			"  TurnRows(): QueryRecipeBuilder;",
			"  ToolRows(): QueryRecipeBuilder;",
			"  EventRows(): QueryRecipeBuilder;",
			"  TurnBlockRows(): QueryRecipeBuilder;",
			"  TokenUsageRows(): QueryRecipeBuilder;",
			"  TranscriptRows(): QueryRecipeBuilder;",
			"  TimelineRows(): QueryRecipeBuilder;",
			"  SessionID(id: string): QueryRecipeBuilder;",
			"  IncludeTools(enabled?: boolean): QueryRecipeBuilder;",
			"  BySession(): QueryRecipeBuilder;",
			"  ByTurn(): QueryRecipeBuilder;",
			"  ByRole(): QueryRecipeBuilder;",
			"  ByTool(): QueryRecipeBuilder;",
			"  Build(): QueryRecipe;",
			"}",
			"export interface ViewPlanBuilder {",
			"  DB(db: DBHandle): ViewPlanBuilder;",
			"  SessionID(id: string): ViewPlanBuilder;",
			"  Transcript(): ViewPlanBuilder;",
			"  TurnFrames(): ViewPlanBuilder;",
			"  Timeline(): ViewPlanBuilder;",
			"  TokenUsage(): ViewPlanBuilder;",
			"  SessionSummary(): ViewPlanBuilder;",
			"  IncludeTools(enabled?: boolean): ViewPlanBuilder;",
			"  IncludeThinking(enabled?: boolean): ViewPlanBuilder;",
			"  IncludeToolResults(enabled?: boolean): ViewPlanBuilder;",
			"  CollapseLongTextAt(chars: number): ViewPlanBuilder;",
			"  BySession(): ViewPlanBuilder;",
			"  ByTurn(): ViewPlanBuilder;",
			"  ByRole(): ViewPlanBuilder;",
			"  ByTool(): ViewPlanBuilder;",
			"  Plan(): QueryRecipe;",
			"  Run(): unknown;",
			"}",
			"export interface SessionBuilder {",
			"  Sources(sources: SourceSet): SessionBuilder;",
			"  Source(sources: SourceSet): SessionBuilder;",
			"  Import(policy: ImportPolicy): SessionBuilder;",
			"  Cache(policy: CachePolicy): SessionBuilder;",
			"  Limits(limits: QueryLimits): SessionBuilder;",
			"  SessionID(id: string): SessionBuilder;",
			"  File(path: string): SessionBuilder;",
			"  Content(content: string): SessionBuilder;",
			"  Name(name: string): SessionBuilder;",
			"  InteractiveCache(cacheDir?: string): SessionBuilder;",
			"  Strict(enabled?: boolean): SessionBuilder;",
			"  Open(): SessionHandle;",
			"}",
			"export interface SessionHandle {",
			"  id(): string;",
			"  summary(): Record<string, unknown>;",
			"  diagnostics(): Array<Record<string, unknown>>;",
			"  cacheInfo(): Record<string, unknown>;",
			"  db(): DBHandle;",
			"  query(sql: string, ...args: unknown[]): Array<Record<string, unknown>>;",
			"  view(): ViewPlanBuilder;",
			"  close(): void;",
			"}",
		},
	}
}
