// Code generated by logcopter-gen; DO NOT EDIT.

package minitracecmd

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-minitrace.pkg.minitracecmd")
