__section__("report", {
  title: "Markdown report",
  fields: {
    out: {
      type: "string",
      default: "./dist/report",
      help: "Directory that receives minitrace-summary.md",
    },
    title: {
      type: "string",
      default: "Minitrace Smoke Report",
      help: "Markdown report title",
    },
  },
});

function markdownSummary(report) {
  const mt = require("minitrace");
  const fs = require("fs");

  const summary = mt.legacy.queryOne(`
    SELECT
      COUNT(*) AS session_count,
      SUM(CAST(metrics->>'tool_call_count' AS BIGINT)) AS tool_call_count,
      SUM(CAST(metrics->>'turn_count' AS BIGINT)) AS turn_count
    FROM ${mt.legacy.tableName}
  `);
  const rows = mt.legacy.query(`
    SELECT
      id,
      title,
      environment->>'agent_framework' AS framework,
      operational_context->>'working_directory' AS workspace,
      CAST(metrics->>'tool_call_count' AS BIGINT) AS tools
    FROM ${mt.legacy.tableName}
    ORDER BY id ASC
  `);

  fs.mkdirSync(report.out, { recursive: true });
  const outputPath = `${report.out.replace(/\/$/, "")}/minitrace-summary.md`;
  const lines = [
    `# ${report.title}`,
    "",
    `Generated by an xgoja-mounted go-minitrace command provider.`,
    "",
    `- Runtime command: ${mt.runtime.commandName}`,
    `- Table: ${mt.legacy.tableName}`,
    `- Sessions: ${summary.session_count}`,
    `- Tool calls: ${summary.tool_call_count}`,
    `- Turns: ${summary.turn_count}`,
    "",
    "## Sessions",
    "",
    "| id | framework | tools | workspace | title |",
    "| --- | --- | ---: | --- | --- |",
    ...rows.map((row) => `| ${row.id} | ${row.framework} | ${row.tools} | ${row.workspace} | ${row.title} |`),
    "",
  ];
  fs.writeFileSync(outputPath, lines.join("\n"), "utf8");
  return {
    report_path: outputPath,
    session_count: summary.session_count,
    tool_call_count: summary.tool_call_count,
    first_title: rows[0]?.title || "",
  };
}

__verb__("markdownSummary", {
  name: "markdown-summary",
  short: "Write a Markdown report using minitrace queries and require(\"fs\")",
  fields: { report: { bind: "report" } },
});
