__section__("report", {
  title: "Markdown report",
  fields: {
    out: { type: "string", default: "./dist/report", help: "Directory that receives minitrace-summary.md" },
    title: { type: "string", default: "Minitrace Smoke Report", help: "Markdown report title" },
  },
});

function markdownSummary(report) {
  const mt = require("minitrace");
  const fs = require("fs");
  const db = mt.db().RuntimeArchives().Build();

  const summary = db.queryOne(`
    SELECT
      COUNT(*) AS session_count,
      SUM(tool_call_count) AS tool_call_count,
      SUM(turn_count) AS turn_count
    FROM sessions
  `);
  const rows = db.query(`
    SELECT
      session_id AS id,
      title,
      agent_framework AS framework,
      working_directory AS workspace,
      tool_call_count AS tools
    FROM sessions
    ORDER BY session_id ASC
  `);

  fs.mkdirSync(report.out, { recursive: true });
  const outputPath = `${report.out.replace(/\/$/, "")}/minitrace-summary.md`;
  const lines = [
    `# ${report.title}`,
    "",
    `Generated by an xgoja-mounted go-minitrace command provider.`,
    "",
    `- Runtime command: ${mt.runtime.commandName}`,
    `- Data source: mt.db().RuntimeArchives()`,
    `- Sessions: ${summary.session_count}`,
    `- Tool calls: ${summary.tool_call_count}`,
    `- Turns: ${summary.turn_count}`,
    "",
    "## Sessions",
    "",
    "| id | framework | tools | workspace | title |",
    "| --- | --- | ---: | --- | --- |",
    ...rows.map((row) => `| ${row.id} | ${row.framework} | ${row.tools} | ${row.workspace} | ${row.title} |`),
    "",
  ];
  fs.writeFileSync(outputPath, lines.join("\n"), "utf8");
  return {
    report_path: outputPath,
    session_count: summary.session_count,
    tool_call_count: summary.tool_call_count,
    first_title: rows[0]?.title || "",
  };
}

__verb__("markdownSummary", {
  name: "markdown-summary",
  short: "Write a Markdown report using mt.db() and require(\"fs\")",
  fields: { report: { bind: "report" } },
});
